# Generated by Django 3.2.20 on 2023-09-18 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_management', '0002_remove_eventposter_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='poster_images')),
            ],
        ),
        migrations.DeleteModel(
            name='EventPoster',
        ),
    ]
